apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  # The name of the entity. This name is both meant for human eyes to recognize the entity, and for machines and other components to reference the entity. Must be unique.
  name: internal-application
  title: title internal application
  description: desc internal application
  annotations:
    dev.azure.com/project-repo: internal application repository
    backstage.io/source-location: url:https://dev.azure.com/pandurx/repo-location
  tags:
    - cloud
  links:
    - url: https://google.com
      title: internal application
spec:
  owner: vikings
  type: website
  lifecycle: production
  domain: certification
